app = "aptgforwardv3"   # <-- all lowercase, no underscore
primary_region = "sin"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python bot.py"

# âŒ Do not include [build] if you already have Dockerfile
